### PR TITLE
added support for touchscreen

### PR DESCRIPTION
**Pull request by minovap**
I created a component that pulls touch events from the M5Unified instance. I also included a example esphome config that implements it.

### CODE REVIEW

**Comment by lboue** [comment]
I've tested it and it works well.

unnamed

**Comment by minovap** [comment]
Ok, great 👍 You can merge the pull request to the main repo so others can
use it 🙂

**Comment by lboue** [comment]
image

**Comment by Forairaaaaa** [comment]
Thanks!

**Pull request merged**
